name: fadaalhalij
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.2


dependencies:

  flutter:
    sdk: flutter
  bloc: ^9.0.0
  bloc_test: ^10.0.0
  blur: ^4.0.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  device_info_plus: ^11.3.0
  dio: ^5.7.0
  firebase_analytics: ^11.3.6
  firebase_crashlytics: ^4.2.0
  flutter_bloc: ^9.0.0
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.14
  get_it: ^8.0.2
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  injectable: ^2.5.0
  intl: any
  json_annotation: ^4.9.0
  lottie: ^3.1.3
  cupertino_icons: ^1.0.8
  percent_indicator: ^4.2.4
  permission_handler: ^11.3.1
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.1
  shared_preferences: ^2.3.3
  skeletonizer: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  lints: ^5.0.0
  retrofit_generator: ^9.1.4




flutter:
  generate: true

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/images/image_default.jpg

